"""CREW 3: Review & Polish Crew

This crew performs comprehensive quality assurance, brand alignment, and SEO
optimization on all content generated by CREW 2. Three specialized agents work
sequentially to ensure content meets professional standards before publication.

Architecture:
- 3 agents working SEQUENTIALLY (not parallel due to CrewAI limitations)
- 12 tools total (4 per agent)
- Process.sequential for reliable execution
- Input: CREW 2 outputs + CREW 1 research artifacts
- Output: Review reports with actionable recommendations

Expected Runtime: 15-20 minutes (60 RPM rate limit)

Agents:
1. Quality Assurance Reviewer (Agent #8)
   - AccuracyChecker, ConsistencyValidator, ReadabilityAnalyzer, LinkValidator
   - Reviews content for accuracy, consistency, readability, CTAs

2. Brand Voice Guardian (Agent #9)
   - ToneAnalyzer, MessagingAligner, PersonaValidator, ComplianceChecker
   - Ensures brand voice, messaging alignment, persona fit, compliance

3. SEO Optimizer (Agent #10)
   - KeywordOptimizer, MetadataGenerator, CTAEnhancer, FormatOptimizer
   - Optimizes for search visibility, metadata, CTAs, formatting

Integration with Pipeline:
- CREW 1 (Research) → CREW 2 (Generation) → CREW 3 (Review) → HITL Flow
- Gate 4 (HITL) placed AFTER this crew to allow human review of final content
"""

import os
from pathlib import Path
from crewai import Agent, Crew, Process, Task, LLM
from crewai.project import CrewBase, agent, crew, task
from crewai_tools import FileReadTool

from b2b_content_agent.llm_manager import get_llm_manager
from b2b_content_agent.tools.qa_review_tools import (
    AccuracyChecker,
    ConsistencyValidator,
    ReadabilityAnalyzer,
    LinkValidator
)
from b2b_content_agent.tools.brand_voice_tools import (
    ToneAnalyzer,
    MessagingAligner,
    PersonaValidator,
    ComplianceChecker
)
from b2b_content_agent.tools.seo_optimization_tools import (
    KeywordOptimizer,
    MetadataGenerator,
    CTAEnhancer,
    FormatOptimizer
)


@CrewBase
class ReviewPolishCrew:
    """Review & Polish Crew for content quality assurance and optimization."""
    
    # Configuration files
    agents_config = 'config/crew3_agents.yaml'
    tasks_config = 'config/crew3_tasks.yaml'
    
    def __init__(self):
        """Initialize the crew with LLM manager for multi-provider support."""
        # Initialize LLM manager
        self.llm_manager = get_llm_manager()
        
        # Use flash model for all agents (fast, reliable)
        self.llm_flash = self.llm_manager.get_llm("flash", temperature=0.7)
        
        # Initialize shared tools
        self.file_read_tool = FileReadTool()
    
    # ==================== AGENT DEFINITIONS ====================
    
    @agent
    def quality_assurance_reviewer(self) -> Agent:
        """Agent #8: Quality Assurance Reviewer
        
        Performs comprehensive quality checks on generated content including
        accuracy verification, consistency validation, readability analysis,
        and CTA effectiveness assessment.
        """
        return Agent(
            config=self.agents_config['quality_assurance_reviewer'],
            tools=[
                AccuracyChecker(),
                ConsistencyValidator(),
                ReadabilityAnalyzer(),
                LinkValidator(),
                self.file_read_tool
            ],
            llm=self.llm_flash,
            verbose=False,
            allow_delegation=False
        )
    
    @agent
    def brand_voice_guardian(self) -> Agent:
        """Agent #9: Brand Voice Guardian
        
        Ensures content aligns with brand voice, messaging strategy, persona
        requirements, and compliance standards. Maintains brand integrity
        across all content.
        """
        return Agent(
            config=self.agents_config['brand_voice_guardian'],
            tools=[
                ToneAnalyzer(),
                MessagingAligner(),
                PersonaValidator(),
                ComplianceChecker(),
                self.file_read_tool
            ],
            llm=self.llm_flash,
            verbose=False,
            allow_delegation=False
        )
    
    @agent
    def seo_optimizer(self) -> Agent:
        """Agent #10: SEO Optimizer
        
        Optimizes content for search visibility and conversion effectiveness
        through keyword optimization, metadata generation, CTA enhancement,
        and format improvements.
        """
        return Agent(
            config=self.agents_config['seo_optimizer'],
            tools=[
                KeywordOptimizer(),
                MetadataGenerator(),
                CTAEnhancer(),
                FormatOptimizer(),
                self.file_read_tool
            ],
            llm=self.llm_flash,
            verbose=False,
            allow_delegation=False
        )
    
    # ==================== TASK DEFINITIONS ====================
    
    @task
    def qa_review_task(self) -> Task:
        """Task 1: Quality Assurance Review
        
        Comprehensive quality check covering accuracy, consistency, readability,
        and CTAs. Produces detailed QA report with specific, actionable feedback.
        """
        return Task(
            config=self.tasks_config['qa_review_task'],
            agent=self.quality_assurance_reviewer()
        )
    
    @task
    def brand_review_task(self) -> Task:
        """Task 2: Brand Voice & Compliance Review
        
        Validates brand voice consistency, messaging alignment, persona relevance,
        and compliance requirements. Ensures content maintains brand integrity.
        """
        return Task(
            config=self.tasks_config['brand_review_task'],
            agent=self.brand_voice_guardian()
        )
    
    @task
    def seo_optimization_task(self) -> Task:
        """Task 3: SEO & Format Optimization
        
        Optimizes content for search visibility and conversion through keyword
        optimization, metadata generation, CTA enhancement, and format improvements.
        """
        return Task(
            config=self.tasks_config['seo_optimization_task'],
            agent=self.seo_optimizer()
        )
    
    # ==================== CREW DEFINITION ====================
    
    @crew
    def crew(self) -> Crew:
        """Assemble the Review & Polish Crew.
        
        Sequential Process:
        1. QA Review (accuracy, consistency, readability, CTAs)
        2. Brand Review (tone, messaging, persona, compliance)
        3. SEO Optimization (keywords, metadata, CTAs, format)
        
        Returns comprehensive review reports for human evaluation at Gate 4.
        """
        return Crew(
            agents=[
                self.quality_assurance_reviewer(),
                self.brand_voice_guardian(),
                self.seo_optimizer()
            ],
            tasks=[
                self.qa_review_task(),
                self.brand_review_task(),
                self.seo_optimization_task()
            ],
            process=Process.sequential,
            verbose=False
        )


def run_review_polish(input_params: dict = None) -> dict:
    """Run the Review & Polish crew on generated content.
    
    Args:
        input_params: Dictionary containing:
            - content_files: Paths to CREW 2 output files
            - research_artifacts: Paths to CREW 1 outputs (strategy, persona)
            - target_keywords: Keywords for SEO optimization
            - brand_guidelines: Brand voice and tone requirements
            
    Returns:
        Dictionary with review reports and recommendations
    """
    
    # Ensure output directory exists
    output_dir = Path("output/reviews")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\n" + "="*80)
    print("CREW 3: REVIEW & POLISH - STARTING")
    print("="*80)
    print("\nThis crew will review and optimize all generated content.")
    print("Process: SEQUENTIAL execution (15-20 minutes)")
    print("\nAgents working:")
    print("  1. Quality Assurance Reviewer (accuracy, consistency, readability)")
    print("  2. Brand Voice Guardian (tone, messaging, persona, compliance)")
    print("  3. SEO Optimizer (keywords, metadata, CTAs, formatting)")
    print("\n" + "="*80 + "\n")
    
    # Initialize and run crew
    crew = ReviewPolishCrew()
    result = crew.crew().kickoff(inputs=input_params or {})
    
    print("\n" + "="*80)
    print("CREW 3: REVIEW & POLISH - COMPLETED")
    print("="*80)
    print(f"\nReview reports saved to: {output_dir.absolute()}")
    print("\nNext Step: Gate 4 - Human review of content and recommendations")
    print("="*80 + "\n")
    
    return result


if __name__ == "__main__":
    """Run the Review & Polish crew for testing.
    
    This script expects CREW 2 outputs to be available in output/ directories.
    """
    
    # Example input parameters
    input_params = {
        "content_files": {
            "case_study": "output/case_studies/case_study_final.md",
            "white_paper": "output/white_papers/white_paper_final.md",
            "pitch_deck": "output/pitch_decks/pitch_deck_final.md",
            "social_posts": "output/social_media/social_posts_final.md"
        },
        "research_artifacts": {
            "content_strategy": "output/research/content_strategy.md",
            "persona_profile": "output/research/persona_profile.md"
        },
        "target_keywords": "sales productivity, CRM automation, forecast accuracy, pipeline management",
        "brand_guidelines": "Professional but approachable, confident without being salesy, consultative voice"
    }
    
    result = run_review_polish(input_params)
    print("\nReview complete!")
    print(f"Results: {result}")
